- hosts: primary
  roles:
    - ensure-python
    - ensure-pip
  tasks:
    - name: Install Helm
      shell: |
        TMP_DIR=$(mktemp -d)
        curl -sSL https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz | tar -zxv --strip-components=1 -C ${TMP_DIR}
        mv "${TMP_DIR}"/helm /usr/local/bin/helm
        rm -rf "${TMP_DIR}"
        sudo -H pip3 install --upgrade yq bandit=={{ bandit_version }} setuptools
      environment:
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Template out python files
      shell: |
        set -xe;
        make all
        mkdir -p python-files
        ./tools/gate/files/template-python.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Run bandit against python files
      shell: bandit -r ./python-files
      args:
        chdir: "{{ zuul.project.src_dir }}"
